# 服务端口
server:
  port: 8080
spring:
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: 8858
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
    timeout: 6000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/myemail_db?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 2835
  servlet:
    multipart:
      max-file-size: 10MB # 设置单个文件的大小为10M
      max-request-size: 50MB # 设置总上传的数据大小为50M
# 配置mybatis
mybatis:
  mapper-locations: classpath*:mapper/*.xml
#logging:
#  level:
#    xyz.pplax.mymail.*.mapper: trace


# 自定义参数
pplax:
  file:
    savepath: G:\\tmp\\mymail\\

